# first directive hosts to which apply

---
- hosts: all
  become: true
  roles:
   - basic

- hosts: webserver
  become: true
  vars: 
  - http_port: 80
  - WelcomeHomeMsg: "Home Page"
  remote_user: deploy
  roles:
   - webserver   

- hosts: appserver
  become: true
  roles:
   - appserver    

- hosts: dbserver
  become: true
  roles:
   - dbserver  